### ISSUE TITLE
Background color is black

### ISSUE THREAD

**Issue by sorashi** [svrana/neosolarized.nvim#10]
I don't know whether this is intended behavior or if I'm doing something wrong. The theme sets the background color to black.

![image](https://user-images.githubusercontent.com/6270283/200444897-d162b737-10a0-4f31-9904-0f3e25231c6b.png)

I even tried it in a clean nvim config using only `init.lua`:

https://gist.github.com/sorashi/9f144e5aa33c1be480d2e675418bc53d

The result is the same.

---

The background color is set to the solarized background color when I do this using colorbuddy

```lua
Group.new('Normal', colors.base0, colors.base03, styles.NONE)
Group.new('NormalNC', colors.base0:dark(), colors.base03, styles.NONE)
```

![image](https://user-images.githubusercontent.com/6270283/200445099-825fe48f-9a13-4dce-9b5b-d4ef6f0a4c2d.png)

(although notice the line number 1 background is still black)

---

The issue appears in all terminals when using nvim (wezterm, gnome-terminal, black box). It also appears in neovide.

`nvim --version` v0.8.0

**Comment by svrana** [comment]
My guess would be that your terminal is not properly setup for true color, but I could be wrong.

Run one of the tests described here to test for support:
https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern

**Comment by svrana** [comment]
Ok, so did some testing. If I change my terminal background from the solarized background color to black, I see the same thing you do, so this colorscheme is making some assumptions.

Should probably add some code to optionally? set the appropriate background colors for those not running a solarized terminal or using an embedded neovim.

**Comment by svrana** [comment]
LineNr is the one your missing, I think.

You might try:
Group.new('LineNr', colors.base01, colors.base03, styles.NONE) 

But may be a few others.

**Comment by sorashi** [comment]
> My guess would be that your terminal is not properly setup for true color, but I could be wrong.
> 
> Run one of the tests described here to test for support: [unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern](https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern)

![image](https://user-images.githubusercontent.com/6270283/200542800-d05dbb97-6464-4ffc-95ec-036caa51c1a3.png)

```bash
> echo $TERM
xterm-256color
```

> Ok, so did some testing. If I change my terminal background from the solarized background color to black, I see the same thing you do, so this colorscheme is making some assumptions.
> 
> Should probably add some code to optionally? set the appropriate background colors for those not running a solarized terminal or using an embedded neovim.

That would be awesome, I don't know the correct highlight groups to set, unfortunately.

> `Group.new('LineNr', colors.base01, colors.base03, styles.NONE)`

I'll add that one, thanks.

**Comment by nicos68** [comment]
Same issue here. The fix also works.

**Comment by svrana** [comment]
Should be fixed if you update to the latest commit and set `background_set' to true in the neosolarized setup function.
