### ISSUE TITLE
Unknown setting: background_color

### ISSUE THREAD

**Issue by travisariggs** [svrana/neosolarized.nvim#17]
I really appreciate your colorscheme.

It works great, except that I see this error message in my statusline on starting up neovim 0.8.1:

```
neosolarized: unknown setting:  background_color
```

My settings do specify that as a parameter. 

```
n = require("neosolarized").setup({
  comment_italics = true,
  background_set = true,
  background_color = require("colorbuddy.init").Color.new("custom_bg", "#00252E")
})

n.Group.new('PreProc', n.colors.yellow)
n.Group.new("NormalNC", n.colors.base0, n.bg_color)
```

The really strange part is that it actually does work; it just complains about the setting.

Am I doing something wrong with my settings?  I am not a Lua developer.

**Comment by svrana** [comment]
I tried your config and then tweaked it a bit.. both resulted in the behavior you describe above.
```
local Color, colors, Group, groups, styles = require('colorbuddy').setup()
Color.new("custom_bg", "#00252E")

local n = require('neosolarized').setup({
             comment_italics = true,
             background_set = true, -- set this to false if you use transparency in your terminal window
             background_color = colors.custom_bg,
})
-- for some reason some code actions get highlighted with WarningMsg and it's too much for me
n.Group.link('WarningMsg', n.groups.Comment)
```
Definitely a bug. Will try to fix tonight.

**Comment by svrana** [comment]
Went ahead and pushed a "fix" so you stop seeing the erroring.

**Comment by travisariggs** [comment]
Excellent! Thank you for the quick response! The error message on my setup is gone.
