### ISSUE TITLE
Colors not correct in iTerm2

### ISSUE THREAD

**Issue by netikular** [svrana/neosolarized.nvim#19]
I was trying out the colorscheme as the one that I'm currently doesn't support the newer features of nvim.

I loaded it and it obviously didn't work:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/62773/225755533-5c10aa69-1f0e-4066-8332-506f1ba38e89.png">

So I tried the original neosolarized and that one works correctly.

I'm using Lazy as a package manager and this is my config:
```
  'tjdevries/colorbuddy.nvim',
  {
    'svrana/neosolarized.nvim',
    config = function()
      vim.cmd.colorscheme 'neosolarized'
    end,
  },
```

Is there something extra that needs to be configured to get it to work?

**Comment by svrana** [comment]
You might try the setup instructions included in the readme. :P

**Comment by netikular** [comment]
yah, that wasn't clear until I read it again for the 100th time.....
