### ISSUE TITLE
Colorbuddy plugin is not loaded properly due to typo in plugin name

### ISSUE THREAD

**Issue by diego-gt** [svrana/neosolarized.nvim#2]
When installing using Packer, in my `init.lua` file, I get this once I reload neovim:
```
Error detected while processing /home/dg/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...pack/packer/start/neosolarized.nvim/lua/neosolarized.lua:28: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/col
orbuddy.nvim"
stack traceback:
        [C]: in function 'cmd'
        ...pack/packer/start/neosolarized.nvim/lua/neosolarized.lua:28: in function 'setup'
        /home/dg/.config/nvim/init.lua:77: in main chunk
Press ENTER or type command to continue
```

Following the error details, it looks like there's a typo in the plugin extension, currently it's `.nvim` but the repo it's really called `colorbuddy.vim`.

Very simple fix on line 29 of `neosolarized.lua`. Should I submit a PR?

**Comment by svrana** [comment]
Hmm, colorboddy repo is at  https://github.com/tjdevries/colorbuddy.nvim so I'd think it'd be stored by packer on disk as colorbuddy.nvim.  Is that the same repo you're using to get packer to install colorbuddy?

**Comment by diego-gt** [comment]
Yeah, I was thinking this was strange. Looks to be a typo on MY end. I installed it using `.vim` but guess Packer was able to redirect to the correct repo but didn't change the folder name. Didn't notice it. Sorry about that.

**Comment by svrana** [comment]
oh, https://github.com/tjdevries/colorbuddy.vim does redirect.. perhaps tj renamed the project at some point.

Glad you got it working!

**Comment by pmyjavec** [comment]
Having the same problem, in my case it might have to do with the fact I'm installing with [vim-pug](https://github.com/junegunn/vim-plug)
