### ISSUE TITLE
`FoldColumn` has different bg from `LineNr` and `SignColumn`

### ISSUE THREAD

**Issue by loqusion** [svrana/neosolarized.nvim#21]
Before:

<img width="1416" alt="Screenshot 2023-04-23 at 7 13 13 AM" src="https://user-images.githubusercontent.com/38332081/233839140-f24bd2bc-7437-4b4c-b8ea-2cbcf8ce0c2f.png">

After `hi FoldColumn guibg=NONE`:

<img width="1416" alt="Screenshot 2023-04-23 at 7 14 53 AM" src="https://user-images.githubusercontent.com/38332081/233839245-3259ca84-82b6-431b-b4d9-298be7d1998f.png">

**Comment by svrana** [comment]
Making them the same seems reasonable to me. Would you like to submit a patch?
