### ISSUE TITLE
Transparency settings not honored for mason popup

### ISSUE THREAD

**Issue by RiteshChepuri** [svrana/neosolarized.nvim#23]
Colorscheme works perfectly fine for every plugin which has floating windows. but it doesnt seem to work with the mason. I have changed winblend options and tried. I thought the problem is within the mason but when i tried it with catppuccin it worked fine. I think there is no support for mason. Please look into it.

**Comment by svrana** [comment]
Hi @RiteshChepuri, I don't use mason but installed it and ran :Mason and this what I got.

![image](https://github.com/svrana/neosolarized.nvim/assets/850665/45569d67-ed10-452d-9702-6536d816b3b8)

Is there a particular screen that doesn't look right on your side?

I'm using background_set=true as I do not use transparency, perhaps there is a difference there too?

**Comment by RiteshChepuri** [comment]
Yeah same for me too.I am expecting something like this
![Screenshot from 2023-05-20 06-53-22](https://github.com/svrana/neosolarized.nvim/assets/81766942/b0946646-43f6-4a18-a26b-791fa09aab87)
but i am getting this. I am trying to find a fix.
![Screenshot from 2023-05-20 06-53-00](https://github.com/svrana/neosolarized.nvim/assets/81766942/e6edd516-4488-4891-8ae7-a00fa22e3bad)
I thought it was a issue with mason but it worked fine the catppuccin theme 
![Screenshot from 2023-05-20 06-56-19](https://github.com/svrana/neosolarized.nvim/assets/81766942/2213c7a0-d8d2-4dcc-b3a3-10d1c59d2e1f)
i am trying to acheive this.
